export const marineCategories = [
  { id: 1, name: "Navigation Systems", slug: "navigation-systems" },
  { id: 2, name: "Fish Finders & Sonar", slug: "fish-finders-sonar" },
  { id: 3, name: "Marine Communication", slug: "marine-communication" },
  { id: 5, name: "Autopilot Systems", slug: "autopilot-systems" },
  { id: 6, name: "Digital Radar", slug: "digital-radar" },
  { id: 7, name: "Chartplotters", slug: "chartplotters" },
];

export const marineBrands = [
  { id: 1, name: "Garmin", logo: "https://upload.wikimedia.org/wikipedia/commons/5/56/Garmin_logo.svg" },
  { id: 2, name: "Raymarine", logo: "https://seeklogo.com/images/R/raymarine-logo-1CE4ACBB5A-seeklogo.com.png" },
  { id: 3, name: "Furuno", logo: "https://upload.wikimedia.org/wikipedia/commons/4/40/Furuno_logo.svg" },
  { id: 4, name: "Lowrance", logo: "https://upload.wikimedia.org/wikipedia/commons/3/33/Lowrance_logo.svg" },
  { id: 5, name: "Simrad", logo: "https://upload.wikimedia.org/wikipedia/commons/e/e7/Simrad_logo.svg" },
  { id: 6, name: "B&G", logo: "https://upload.wikimedia.org/wikipedia/commons/0/0c/B%26G-logo.svg" },
  { id: 7, name: "Humminbird", logo: "https://upload.wikimedia.org/wikipedia/commons/7/78/Humminbird_logo.svg" },
  // { id: 8, name: "JL Audio", logo: "https://seeklogo.com/images/J/jl-audio-logo-84C7C16C24-seeklogo.com.png" },
  { id: 9, name: "Icom", logo: "https://upload.wikimedia.org/wikipedia/commons/3/3a/Icom_Logo.svg" },
  // { id: 10, name: "Standard Horizon", logo: "https://seeklogo.com/images/S/standard-horizon-logo-2F887C7C2C-seeklogo.com.png" },
  // { id: 11, name: "KVH", logo: "https://upload.wikimedia.org/wikipedia/commons/d/de/KVH_Industries_logo.svg" },
];

export const marineProducts = [
  {
    id: 1,
    name: "Garmin GPSMAP 923xsv",
    category: "Navigation Systems",
    brand: "Garmin",
    image: "/item1.jpg",
    isBestSeller: true,
    isNew: false,
  },
  {
    id: 2,
    name: "Raymarine Axiom Pro 12",
    category: "Chartplotters",
    brand: "Raymarine",
    image: "/item2.jpg",
    isBestSeller: true,
    isNew: false,
  },
  {
    id: 3,
    name: "Furuno DRS25 Radar",
    category: "Digital Radar",
    brand: "Furuno",
    image: "/item3.jpg",
    isBestSeller: false,
    isNew: true,
  },
  {
    id: 4,
    name: "Lowrance HDS Pro 16",
    category: "Fish Finders & Sonar",
    brand: "Lowrance",
    image: "/item4.jpg",
    isBestSeller: false,
    isNew: true,
  },
  {
    id: 5,
    name: "Simrad AP44 Autopilot",
    category: "Autopilot Systems",
    brand: "Simrad",
    image: "/item5.jpg",
    isBestSeller: true,
    isNew: false,
  },
  {
    id: 6,
    name: "B&G Zeus 3S 12 Sailing",
    category: "Chartplotters",
    brand: "B&G",
    image: "/item6.jpg",
    isBestSeller: false,
    isNew: true,
  },
  {
    id: 7,
    name: "Humminbird Helix 15 Mega",
    category: "Fish Finders & Sonar",
    brand: "Humminbird",
    image: "/hero1.jpg",
    isBestSeller: true,
    isNew: false,
  },
  {
    id: 8,
    name: "Icom M506 Marine VHF",
    category: "Marine Communication",
    brand: "Icom",
    image: "/item8.jpg",
    isBestSeller: false,
    isNew: true,
  },
  // {
  //   id: 9,
  //   name: "JL Audio M6 Tower Speakers",
  //   category: "Power & Electrical",
  //   brand: "JL Audio",
  //   image: "/hero1.jpg",
  //   isBestSeller: true,
  //   isNew: false,
  // },
  // {
  //   id: 10,
  //   name: "Fusion Apollo Marine Amplifier",
  //   category: "Power & Electrical",
  //   brand: "Fusion Audio",
  //   image: "/hero1.jpg",
  //   isBestSeller: false,
  //   isNew: true,
  // },
  // {
  //   id: 11,
  //   name: "Ultra Bright Underwater LED",
  //   category: "Underwater Lights",
  //   brand: "Raymarine",
  //   image: "/hero1.jpg",
  //   isBestSeller: false,
  //   isNew: true,
  // },
  // {
  //   id: 12,
  //   name: "OceanPro Emergency Survival Kit",
  //   category: "Safety & Survival Gear",
  //   brand: "Standard Horizon",
  //   image: "/hero1.jpg",
  //   isBestSeller: true,
  //   isNew: false,
  // },
  // {
  //   id: 13,
  //   name: "Garmin inReach Explorer+",
  //   category: "Safety & Survival Gear",
  //   brand: "Garmin",
  //   image: "/hero1.jpg",
  //   isBestSeller: false,
  //   isNew: true,
  // },
  // {
  //   id: 14,
  //   name: "Furuno GP-170",
  //   category: "Navigation Systems",
  //   brand: "Furuno",
  //   image: "/hero1.jpg",
  //   isBestSeller: true,
  //   isNew: false,
  // },
  // {
  //   id: 15,
  //   name: "Lowrance Elite FS 9",
  //   category: "Chartplotters",
  //   brand: "Lowrance",
  //   image: "/hero1.jpg",
  //   isBestSeller: false,
  //   isNew: true,
  // },
  // {
  //   id: 16,
  //   name: "Simrad NSO evo3",
  //   category: "Navigation Systems",
  //   brand: "Simrad",
  //   image: "/hero1.jpg",
  //   isBestSeller: true,
  //   isNew: false,
  // },
  // {
  //   id: 17,
  //   name: "B&G Triton2",
  //   category: "Marine Communication",
  //   brand: "B&G",
  //   image: "/hero1.jpg",
  //   isBestSeller: false,
  //   isNew: true,
  // },
  // {
  //   id: 18,
  //   name: "Humminbird SOLIX G3",
  //   category: "Digital Radar",
  //   brand: "Humminbird",
  //   image: "/hero1.jpg",
  //   isBestSeller: true,
  //   isNew: false,
  // },
  // {
  //   id: 19,
  //   name: "Icom IC-M330",
  //   category: "Autopilot Systems",
  //   brand: "Icom",
  //   image: "/hero1.jpg",
  //   isBestSeller: false,
  //   isNew: true,
  // },
  // {
  //   id: 20,
  //   name: "Standard Horizon GX1400",
  //   category: "Fish Finders & Sonar",
  //   brand: "Standard Horizon",
  //   image: "/hero1.jpg",
  //   isBestSeller: true,
  //   isNew: false,
  // },
  // {
  //   id: 21,
  //   name: "KVH TracVision TV5",
  //   category: "Marine Cameras",
  //   brand: "KVH",
  //   image: "/hero1.jpg",
  //   isBestSeller: false,
  //   isNew: true,
  // },
  // {
  //   id: 22,
  //   name: "Garmin LiveScope Plus",
  //   category: "Underwater Lights",
  //   brand: "Garmin",
  //   image: "/hero1.jpg",
  //   isBestSeller: true,
  //   isNew: false,
  // },
  // {
  //   id: 23,
  //   name: "Raymarine Quantum Radar",
  //   category: "Digital Radar",
  //   brand: "Raymarine",
  //   image: "/hero1.jpg",
  //   isBestSeller: false,
  //   isNew: true,
  // },
  // {
  //   id: 24,
  //   name: "Furuno TZtouch3",
  //   category: "Safety & Survival Gear",
  //   brand: "Furuno",
  //   image: "/hero1.jpg",
  //   isBestSeller: true,
  //   isNew: false,
  // },
  // {
  //   id: 25,
  //   name: "Lowrance Outboard Boost",
  //   category: "Power & Electrical",
  //   brand: "Lowrance",
  //   image: "/hero1.jpg",
  //   isBestSeller: false,
  //   isNew: true,
  // },
  // {
  //   id: 26,
  //   name: "Simrad Halo20 Radar",
  //   category: "Marine Cameras",
  //   brand: "Simrad",
  //   image: "/hero1.jpg",
  //   isBestSeller: true,
  //   isNew: false,
  // },
  // {
  //   id: 27,
  //   name: "B&G V50 VHF",
  //   category: "Marine Communication",
  //   brand: "B&G",
  //   image: "/hero1.jpg",
  //   isBestSeller: false,
  //   isNew: true,
  // },
  // {
  //   id: 28,
  //   name: "Humminbird 360 Imaging",
  //   category: "Navigation Systems",
  //   brand: "Humminbird",
  //   image: "/hero1.jpg",
  //   isBestSeller: true,
  //   isNew: false,
  // },
  // {
  //   id: 29,
  //   name: "JL Audio M1000/1 Amplifier",
  //   category: "Autopilot Systems",
  //   brand: "JL Audio",
  //   image: "/hero1.jpg",
  //   isBestSeller: false,
  //   isNew: true,
  // },
  // {
  //   id: 30,
  //   name: "KVH CommBox V3",
  //   category: "Power & Electrical",
  //   brand: "KVH",
  //   image: "/hero1.jpg",
  //   isBestSeller: true,
  //   isNew: false,
  // },
];