export const marineCategories = [
  { id: 1, name: "Navigation Systems", slug: "navigation-systems" },
  { id: 2, name: "Fish Finders & Sonar", slug: "fish-finders-sonar" },
  { id: 3, name: "Marine Communication", slug: "marine-communication" },
  { id: 4, name: "Safety & Survival Gear", slug: "safety-survival" },
  { id: 5, name: "Autopilot Systems", slug: "autopilot-systems" },
  { id: 6, name: "Digital Radar", slug: "digital-radar" },
  { id: 7, name: "Chartplotters", slug: "chartplotters" },
  { id: 8, name: "Marine Cameras", slug: "marine-cameras" },
  { id: 9, name: "Power & Electrical", slug: "power-electrical" },
  { id: 10, name: "Underwater Lights", slug: "underwater-lights" },
];

export const marineBrands = [
  { id: 1, name: "Garmin", logo: "https://upload.wikimedia.org/wikipedia/commons/5/56/Garmin_logo.svg" },
  { id: 2, name: "Raymarine", logo: "https://seeklogo.com/images/R/raymarine-logo-1CE4ACBB5A-seeklogo.com.png" },
  { id: 3, name: "Furuno", logo: "https://upload.wikimedia.org/wikipedia/commons/4/40/Furuno_logo.svg" },
  { id: 4, name: "Lowrance", logo: "https://upload.wikimedia.org/wikipedia/commons/3/33/Lowrance_logo.svg" },
  { id: 5, name: "Simrad", logo: "https://upload.wikimedia.org/wikipedia/commons/e/e7/Simrad_logo.svg" },
  { id: 6, name: "B&G", logo: "https://upload.wikimedia.org/wikipedia/commons/0/0c/B%26G-logo.svg" },
  { id: 7, name: "Humminbird", logo: "https://upload.wikimedia.org/wikipedia/commons/7/78/Humminbird_logo.svg" },
  { id: 8, name: "JL Audio", logo: "https://seeklogo.com/images/J/jl-audio-logo-84C7C16C24-seeklogo.com.png" },
  { id: 9, name: "Icom", logo: "https://upload.wikimedia.org/wikipedia/commons/3/3a/Icom_Logo.svg" },
  { id: 10, name: "Standard Horizon", logo: "https://seeklogo.com/images/S/standard-horizon-logo-2F887C7C2C-seeklogo.com.png" },
  { id: 11, name: "KVH", logo: "https://upload.wikimedia.org/wikipedia/commons/d/de/KVH_Industries_logo.svg" },
  { id: 12, name: "Fusion Audio", logo: "https://seeklogo.com/images/F/fusion-logo-4E349C3C9E-seeklogo.com.png" },
];

export const marineProducts = [
  {
    id: 1,
    name: "Garmin GPSMAP 923xsv",
    category: "Navigation Systems",
    brand: "Garmin",
    image: "https://www.garmin.com/en-US/media/products/gpsmap-923xsv/010-02788-00/01/large/010-02788-00-01.png",
    isBestSeller: true,
    isNew: false,
  },
  {
    id: 2,
    name: "Raymarine Axiom Pro 12",
    category: "Chartplotters",
    brand: "Raymarine",
    image: "https://www.raymarine.com/sites/default/files/styles/product_gallery/public/2023-03/E70638_0.png",
    isBestSeller: true,
    isNew: false,
  },
  {
    id: 3,
    name: "Furuno DRS25 Radar",
    category: "Digital Radar",
    brand: "Furuno",
    image: "https://www.furuno.com/media/catalog/product/d/r/drs25_1.png",
    isBestSeller: false,
    isNew: true,
  },
  {
    id: 4,
    name: "Lowrance HDS Pro 16",
    category: "Fish Finders & Sonar",
    brand: "Lowrance",
    image: "https://www.lowrance.com/content/dam/dat-group/lowrance/en/images/products/hds-pro/hds-pro-16-front.png",
    isBestSeller: false,
    isNew: true,
  },
  {
    id: 5,
    name: "Simrad AP44 Autopilot",
    category: "Autopilot Systems",
    brand: "Simrad",
    image: "https://www.simrad-yachting.com/media/products/simrad-ap44-v2-autopilot-system/000-14365-001/01/large/000-14365-001-01.png",
    isBestSeller: true,
    isNew: false,
  },
  {
    id: 6,
    name: "B&G Zeus 3S 12 Sailing",
    category: "Chartplotters",
    brand: "B&G",
    image: "https://www.bandg.com/media/products/zeus3s/000-15510-001/01/large/000-15510-001-01.png",
    isBestSeller: false,
    isNew: true,
  },
  {
    id: 7,
    name: "Humminbird Helix 15 Mega",
    category: "Fish Finders & Sonar",
    brand: "Humminbird",
    image: "https://www.humminbird.com/-/media/humminbird/images/products/helix/helix-15-mega-si-g4/410890-1-helix15-mega-si-g4-front.png",
    isBestSeller: true,
    isNew: false,
  },
  {
    id: 8,
    name: "Icom M506 Marine VHF",
    category: "Marine Communication",
    brand: "Icom",
    image: "https://www.icomamerica.com/lineup/products/IC-M506/IC-M506_image_01.png",
    isBestSeller: false,
    isNew: true,
  },
  {
    id: 9,
    name: "JL Audio M6 Tower Speakers",
    category: "Power & Electrical",
    brand: "JL Audio",
    image: "https://www.jlaudio.com/images/products/marine-audio/m6-770x-s-gwccii-4/m6-770x-s-gwccii-4_1.png",
    isBestSeller: true,
    isNew: false,
  },
  {
    id: 10,
    name: "Fusion Apollo Marine Amplifier",
    category: "Power & Electrical",
    brand: "Fusion Audio",
    image: "https://www.garmin.com/fusion/media/products/apollo-ra770/010-12977-00/01/large/010-12977-00-01.png",
    isBestSeller: false,
    isNew: true,
  },
  {
    id: 11,
    name: "Ultra Bright Underwater LED",
    category: "Underwater Lights",
    brand: "Raymarine",
    image: "https://www.raymarine.com/sites/default/files/styles/product_gallery/public/2023-03/A80294_0.png",
    isBestSeller: false,
    isNew: true,
  },
  {
    id: 12,
    name: "OceanPro Emergency Survival Kit",
    category: "Safety & Survival Gear",
    brand: "Standard Horizon",
    image: "https://www.standardhorizon.com/images/products/gx1400/gx1400_01.jpg",
    isBestSeller: true,
    isNew: false,
  },
  {
    id: 13,
    name: "Garmin inReach Explorer+",
    category: "Safety & Survival Gear",
    brand: "Garmin",
    image: "https://www.garmin.com/en-US/media/products/inreach-explorer-plus/010-01879-00/01/large/010-01879-00-01.png",
    isBestSeller: false,
    isNew: true,
  },
  {
    id: 14,
    name: "Furuno GP-170",
    category: "Navigation Systems",
    brand: "Furuno",
    image: "https://www.furuno.com/media/catalog/product/g/p/gp-170_1.png",
    isBestSeller: true,
    isNew: false,
  },
  {
    id: 15,
    name: "Lowrance Elite FS 9",
    category: "Chartplotters",
    brand: "Lowrance",
    image: "https://www.lowrance.com/content/dam/dat-group/lowrance/en/images/products/elite-fs/elite-fs-9-front.png",
    isBestSeller: false,
    isNew: true,
  },
  {
    id: 16,
    name: "Simrad NSO evo3",
    category: "Navigation Systems",
    brand: "Simrad",
    image: "https://www.simrad-yachting.com/media/products/nso-evo3/000-15522-001/01/large/000-15522-001-01.png",
    isBestSeller: true,
    isNew: false,
  },
  {
    id: 17,
    name: "B&G Triton2",
    category: "Marine Communication",
    brand: "B&G",
    image: "https://www.bandg.com/media/products/triton2/000-13283-001/01/large/000-13283-001-01.png",
    isBestSeller: false,
    isNew: true,
  },
  {
    id: 18,
    name: "Humminbird SOLIX G3",
    category: "Digital Radar",
    brand: "Humminbird",
    image: "https://www.humminbird.com/-/media/humminbird/images/products/solix/solix-g3-12-cv/411170-1-solix-g3-12-cv-front.png",
    isBestSeller: true,
    isNew: false,
  },
  {
    id: 19,
    name: "Icom IC-M330",
    category: "Autopilot Systems",
    brand: "Icom",
    image: "https://www.icomamerica.com/lineup/products/IC-M330/IC-M330_image_01.png",
    isBestSeller: false,
    isNew: true,
  },
  {
    id: 20,
    name: "Standard Horizon GX1400",
    category: "Fish Finders & Sonar",
    brand: "Standard Horizon",
    image: "https://www.standardhorizon.com/images/products/gx1400/gx1400_02.jpg",
    isBestSeller: true,
    isNew: false,
  },
  {
    id: 21,
    name: "KVH TracVision TV5",
    category: "Marine Cameras",
    brand: "KVH",
    image: "https://www.kvh.com/-/media/images/products/satellite-tv-antennas/tracvision-tv-series/tracvision-tv5-s2.png",
    isBestSeller: false,
    isNew: true,
  },
  {
    id: 22,
    name: "Garmin LiveScope Plus",
    category: "Underwater Lights",
    brand: "Garmin",
    image: "https://www.garmin.com/en-US/media/products/livescope-plus-lvs34/010-02332-00/01/large/010-02332-00-01.png",
    isBestSeller: true,
    isNew: false,
  },
  {
    id: 23,
    name: "Raymarine Quantum Radar",
    category: "Digital Radar",
    brand: "Raymarine",
    image: "https://www.raymarine.com/sites/default/files/styles/product_gallery/public/2023-03/E92143_0.png",
    isBestSeller: false,
    isNew: true,
  },
  {
    id: 24,
    name: "Furuno TZtouch3",
    category: "Safety & Survival Gear",
    brand: "Furuno",
    image: "https://www.furuno.com/media/catalog/product/t/z/tztouch3_1.png",
    isBestSeller: true,
    isNew: false,
  },
  {
    id: 25,
    name: "Lowrance Outboard Boost",
    category: "Power & Electrical",
    brand: "Lowrance",
    image: "https://www.lowrance.com/content/dam/dat-group/lowrance/en/images/products/outboard-boost/outboard-boost-front.png",
    isBestSeller: false,
    isNew: true,
  },
  {
    id: 26,
    name: "Simrad Halo20 Radar",
    category: "Marine Cameras",
    brand: "Simrad",
    image: "https://www.simrad-yachting.com/media/products/halo20-pulse-compression-radar/000-13494-001/01/large/000-13494-001-01.png",
    isBestSeller: true,
    isNew: false,
  },
  {
    id: 27,
    name: "B&G V50 VHF",
    category: "Marine Communication",
    brand: "B&G",
    image: "https://www.bandg.com/media/products/v50-vhf/000-11274-001/01/large/000-11274-001-01.png",
    isBestSeller: false,
    isNew: true,
  },
  {
    id: 28,
    name: "Humminbird 360 Imaging",
    category: "Navigation Systems",
    brand: "Humminbird",
    image: "https://www.humminbird.com/-/media/humminbird/images/products/360-imaging/19-1150-1-360-front.png",
    isBestSeller: true,
    isNew: false,
  },
  {
    id: 29,
    name: "JL Audio M1000/1 Amplifier",
    category: "Autopilot Systems",
    brand: "JL Audio",
    image: "https://www.jlaudio.com/images/products/marine-audio/m1000-1v3/m1000-1v3_1.png",
    isBestSeller: false,
    isNew: true,
  },
  {
    id: 30,
    name: "KVH CommBox V3",
    category: "Power & Electrical",
    brand: "KVH",
    image: "https://www.kvh.com/-/media/images/products/vsat-terminals/v3/vsat-v3-commbox.png",
    isBestSeller: true,
    isNew: false,
  },
];