export const marineCategories = [
  { id: 1, name: "Navigation Systems", slug: "navigation-systems" },
  { id: 2, name: "Fish Finders & Sonar", slug: "fish-finders-sonar" },
  { id: 3, name: "Marine Communication", slug: "marine-communication" },
  { id: 4, name: "Safety & Survival Gear", slug: "safety-survival" },
  { id: 5, name: "Autopilot Systems", slug: "autopilot-systems" },
  { id: 6, name: "Digital Radar", slug: "digital-radar" },
  { id: 7, name: "Chartplotters", slug: "chartplotters" },
  { id: 8, name: "Marine Cameras", slug: "marine-cameras" },
  { id: 9, name: "Power & Electrical", slug: "power-electrical" },
  { id: 10, name: "Underwater Lights", slug: "underwater-lights" },
];


export const marineBrands = [
  { id: 1, name: "Garmin", logo: "https://upload.wikimedia.org/wikipedia/commons/5/56/Garmin_logo.svg" },
  { id: 2, name: "Raymarine", logo: "https://seeklogo.com/images/R/raymarine-logo-1CE4ACBB5A-seeklogo.com.png" },
  { id: 3, name: "Furuno", logo: "https://upload.wikimedia.org/wikipedia/commons/4/40/Furuno_logo.svg" },
  { id: 4, name: "Lowrance", logo: "https://upload.wikimedia.org/wikipedia/commons/3/33/Lowrance_logo.svg" },
  { id: 5, name: "Simrad", logo: "https://upload.wikimedia.org/wikipedia/commons/e/e7/Simrad_logo.svg" },
  { id: 6, name: "B&G", logo: "https://upload.wikimedia.org/wikipedia/commons/0/0c/B%26G-logo.svg" },
  { id: 7, name: "Humminbird", logo: "https://upload.wikimedia.org/wikipedia/commons/7/78/Humminbird_logo.svg" },
  { id: 8, name: "JL Audio", logo: "https://seeklogo.com/images/J/jl-audio-logo-84C7C16C24-seeklogo.com.png" },
  { id: 9, name: "Icom", logo: "https://upload.wikimedia.org/wikipedia/commons/3/3a/Icom_Logo.svg" },
  { id: 10, name: "Standard Horizon", logo: "https://seeklogo.com/images/S/standard-horizon-logo-2F887C7C2C-seeklogo.com.png" },
  { id: 11, name: "KVH", logo: "https://upload.wikimedia.org/wikipedia/commons/d/de/KVH_Industries_logo.svg" },
  { id: 12, name: "Fusion Audio", logo: "https://seeklogo.com/images/F/fusion-logo-4E349C3C9E-seeklogo.com.png" },
];

export const marineProducts = [
  {
    id: 1,
    name: "Garmin GPSMAP 923xsv",
    category: "Navigation Systems",
    brand: "Garmin",
    image: "/item1.jpg",
    isBestSeller: true,
    isNew: false,
  },
  {
    id: 2,
    name: "Raymarine Axiom Pro 12",
    category: "Chartplotters",
    brand: "Raymarine",
    image: "/item1.jpg",
    isBestSeller: true,
    isNew: false,
  },
  {
    id: 3,
    name: "Furuno DRS25 Radar",
    category: "Digital Radar",
    brand: "Furuno",
    image: "/item1.jpg",
    isBestSeller: false,
    isNew: true,
  },
  {
    id: 4,
    name: "Lowrance HDS Pro 16",
    category: "Fish Finders & Sonar",
    brand: "Lowrance",
    image: "/item1.jpg",
    isBestSeller: false,
    isNew: true,
  },
  {
    id: 5,
    name: "Simrad AP44 Autopilot",
    category: "Autopilot Systems",
    brand: "Simrad",
    image: "/item1.jpg",
    isBestSeller: true,
    isNew: false,
  },
  {
    id: 6,
    name: "B&G Zeus 3S 12 Sailing",
    category: "Chartplotters",
    brand: "B&G",
    image: "/item1.jpg",
    isBestSeller: false,
    isNew: true,
  },
  {
    id: 7,
    name: "Humminbird Helix 15 Mega",
    category: "Fish Finders & Sonar",
    brand: "Humminbird",
    image: "/item1.jpg",
    isBestSeller: true,
    isNew: false,
  },
  {
    id: 8,
    name: "Icom M506 Marine VHF",
    category: "Marine Communication",
    brand: "Icom",
    image: "/item1.jpg",
    isBestSeller: false,
    isNew: true,
  },
  {
    id: 9,
    name: "JL Audio M6 Tower Speakers",
    category: "Power & Electrical",
    brand: "JL Audio",
    image: "/item1.jpg",
    isBestSeller: true,
    isNew: false,
  },
  {
    id: 10,
    name: "Fusion Apollo Marine Amplifier",
    category: "Power & Electrical",
    brand: "Fusion Audio",
    image: "/item1.jpg",
    isBestSeller: false,
    isNew: true,
  },
  {
    id: 11,
    name: "Ultra Bright Underwater LED",
    category: "Underwater Lights",
    brand: "Raymarine",
    image: "/item1.jpg",
    isBestSeller: false,
    isNew: true,
  },
  {
    id: 12,
    name: "OceanPro Emergency Survival Kit",
    category: "Safety & Survival Gear",
    brand: "Standard Horizon",
    image: "/item1.jpg",
    isBestSeller: true,
    isNew: false,
  },
];
